config/routes.rb
Rails.application.routes.draw do
  resources 'author'
  resources 'exhibition'
  resources 'genre'
  resources 'order'
  resources 'personell'
  resources 'custom'
  resources 'picture'

  get 'welcome/index'
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :pictures
end

app/models/custom.rb
class Custom < ApplicationRecord
  has_many :orders
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  has_many :pictures
  has_many :personnels
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :pictures
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :custom
  belongs_to :personnel

  has_many :pictures
end

app/models/personnel.rb
class Personnel < ApplicationRecord
  belongs_to :exhibition

  has_many :orders
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :order
  belongs_to :author
  belongs_to :genre

  has_many :exhibitions
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def index
  end

  def create
  end

  def delete
  end

  def update
  end
end

app/controllers/custom_controller.rb
class CustomController < ApplicationController
  def index
  end

  def create
  end

  def delete
  end

  def update
  end
end

app/controllers/exhibition_controller.rb
class ExhibitionController < ApplicationController
  def index
  end

  def show
    @pictures = Picture.all
  end

  def create
  end

  def delete
  end

  def update
  end
end

app/controllers/genre_controller.rb
class GenreController < ApplicationController
  def index
  end

  def create
  end

  def delete
  end

  def update
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def index
  end

  def create
  end

  def delete
  end

  def update
  end
end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
  end

  def update
    @picture.update(picture_params)
  end

  def destroy
    @picture.destroy
  end

  private

  def find_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/custom_helper.rb
module CustomHelper
end

app/helpers/exhibition_helper.rb
module ExhibitionHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/personell_helper.rb
module PersonellHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/exhibition/_exhibition.html.slim
.row
  - @exhibitions.each do |exh|
    .col-sm-6.col-md-2.picture
      .thumbnail
        = image_tag("https://image.freepik.com/free-vector/logo-ballons-logotype_355-1165.jpg")
      .caption
        h4
          = link_to exh.location, exhibition_path(exh)
        p
          = exh.date

app/views/exhibition/create.html.slim
h1 Exhibition#create
p Find me in app/views/exhibition/create.html.slim

app/views/exhibition/delete.html.slim
h1 Exhibition#delete
p Find me in app/views/exhibition/delete.html.slim

app/views/exhibition/index.html.slim
h1 Exhibition#index
p Find me in app/views/exhibition/index.html.slim

app/views/exhibition/show.html.slim
.row
  - @pictures.each do |picture|
    .col-sm-6.col-md-2.picture
      .thu style="background-image: url(#{picture.image}); width: 100%; height: 300px;"
      .caption
        h4
          = picture.name
        p
          = picture.date

app/views/exhibition/update.html.slim
h1 Exhibition#update
p Find me in app/views/exhibition/update.html.slim